config/routes.rb
Rails.application.routes.draw do

scope "/admin" do
  resources :games, param: :sku
  get '/' => 'games#index'
  #get '/newgame' => 'games#new'
  #post '/creategame' => 'games#create'
  #get '/game/:sku/edit' => 'games#edit'
  #put '/game/:sku' => 'games#update'
  #patch '/game/:sku' => 'games#update'

end

  root :to => redirect("/site")

  get '/site' => 'site#index'

##scope "/site" do
 # get '/' => 'games#index'
 # get '/game/:sku' => 'games#show'
#end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
	def translated_name
    I18n.t(name)
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :category
  self.primary_key = "sku"
  validates :name, presence: true 
  validates :english_description, presence: true 
  validates :portuguese_description, presence: true 

end

app/models/user.rb
class User < ActiveRecord::Base
	 has_secure_password
	 
	 def User.digest(string)
	  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                BCrypt::Engine.cost
	  BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

  helper_method :current_user, :is_admin?, :cookies

  def authorize
    redirect_to '/login' unless current_user
  end

  def is_admin?
    !current_user.blank?
  end

  before_action :set_locale
 

  def set_locale
    if language_change_necessary?
      I18n.locale = if params[:locale] 
         params[:locale] 
      else 
        I18n.default_locale
      end

      set_locale_cookie(I18n.locale)
    else
      use_locale_from_cookie
    end
    
  end
  

  def set_locale_cookie(locale)
    cookies['locale'] = locale.to_s
  end

 def use_locale_from_cookie
    I18n.locale = cookies['locale']
  end

  # A locale change is necessary if no locale cookie is found, or if the locale param has been specified
  def language_change_necessary?
    return cookies['locale'].nil? || params[:locale]
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authorize, :except => [:show]
  before_action :set_game, only: [:show, :edit, :update, :destroy]


  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end


  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:sku])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :english_description, :portuguese_description, :boxshot, :released, :sku, :category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/admin'
    else
      redirect_to '/'
    end
    
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def index
    @query = params[:q]
    @category_id = 0

    @games = if params.has_key?(:q)
       queryParam = "%" + params[:q] + "%"
       Game.where("name like ? OR english_description like ? OR portuguese_description like ?",queryParam,queryParam,queryParam)
    else
       Game.all
    end

    @games = if params.has_key?(:category) && params[:category][:category_id].to_i > 0
      @category_id = params[:category][:category_id]
      @games.where(category_id: params[:category][:category_id])
    else
      @games
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div id="navbar" class="navbar-collapse collapse">

      <%= link_to image_tag("brazilian_flag.gif"), url_for(params.merge({:locale => 'pt'}))  %>
      <%= link_to image_tag("american_flag.png"),url_for(params.merge({:locale => 'en'})) %>

      <%= link_to 'FooStore', { controller: "site", action: "index" }, class: 'navbar-brand' %>

      <ul class="nav navbar-nav navbar-right">
        <% if is_admin? %>

          <li> <%= link_to 'Admin', { controller: "games", action: "index" } %> </li>
          <li> <%= link_to 'Logout', { controller: "sessions", action: "destroy" }%>  </li>
  
        <%else%>
              <li> <%= link_to 'Login', { controller: "sessions", action: "create" }%> </li>
        <%end%>
      </ul>
     
    </div>
  </div>

</nav>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:name) %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label t(:english_description) %><br>
    <%= f.text_area :english_description %>
  </div>
  <div class="field">
    <%= f.label t(:portuguese_description) %><br>
    <%= f.text_area :portuguese_description %>
  </div>
  <div class="field">
    <%= f.label t(:boxshot) %><br>
    <%= f.text_field :boxshot %>
  </div>
  <div class="field">
    <%= f.label t(:released) %><br>
    <%= f.check_box :released %>
  </div>
  <div class="field">
    <%= f.label t(:category) %><br>
    <%= f.collection_select :category_id, Category.order(:name),:id,:translated_name, include_blank: false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_list.html.erb
<h1><%=t(:games)%></h1>


  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t(:name) %></th>
        <th><%= t(:english_description) %></th>
        <th><%= t(:portuguese_description) %></th>
        <th><%= t(:boxshot) %></th>
        <th><%= t(:released) %></th>
        <th>Sku</th>
        <th><%= t(:category) %></th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.name %></td>
          <td><%= game.english_description %></td>
          <td><%= game.portuguese_description %></td>
          <td><%= game.boxshot %></td>
          <td><%= t(game.released.to_s) %></td>
          <td><%= game.sku %></td>
          <td><%= Category.find(game.category).translated_name %></td>
          <td><%= link_to t(:show), game %></td>

          <% if is_admin? %>
           <td><%= link_to t(:edit), edit_game_path(game) %></td>
           <td><%= link_to t(:destroy), game, method: :delete, data: { confirm: t(:are_you_sure) } %></td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to t(:show), @game, class: "btn-primary" %> |

app/views/games/index.html.erb
<div class="container">
  <%= render 'list' %>

  <% if is_admin? %>
  <%= link_to t(:new_game), new_game_path, class: "btn-primary" %>
  <% end %>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-6">
      <%= image_tag(@game.boxshot,class: 'img-responsive img-rounded')%>
    </div>

    <div class="col-sm-6">
    <p>
      <strong><%= t(:name)+':'%></strong>
      <%= @game.name %>
    </p>

    <p>
      <strong><%= t(:description)+':'%></strong>
        <%if cookies[:locale] == 'pt'%>
         <%= @game.portuguese_description %>
        <%else%>
          <%= @game.english_description %>
        <%end%>
    </p> 

    <% if is_admin? %>
      <p>
        <strong><%= t(:released)+':'%></strong>
        <%= t(@game.released.to_s) %>
      </p>

      <p>
        <strong>Sku:</strong>
        <%= @game.sku %>
      </p>

      <p>
        <strong><%= t(:category)+':'%></strong>
        <%= Category.find(@game.category).translated_name %>
      </p>

    
      <%= link_to t(:edit), edit_game_path(@game), class: "btn-primary" %> 
    <%end%>
   
  </div>

</div>
  
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=t(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<header>

</header>

<%= render 'navbar' %>

<%= yield %>

</body>
</html>

app/views/site/_catalog.html.erb
<div class="container">

<nav class="navbar">
  <div id="navbar" class="navbar-collapse collapse">

  <%= form_tag("/site", method: "get", class:"navbar-form navbar-left", role:"search") do%>
    <%= text_field_tag(:q,@query,class:"form-control", placeholder: t(:search)) %>
    <%= collection_select :category,:category_id, Category.order(:name),:id,:translated_name, {:include_blank  => t(:none),:selected => @category_id}%>
    <%= submit_tag(t(:find), class:"btn btn-default") %>

  <%end%>


  </div>

</nav>
  
   <% i = 0 
    @games.each do |game|
   %>
    <%if i%3 == 0%>
  	   <div class="row">
    <%end%>
  	    <div class="col-md-4">
  	    	<%= link_to image_tag(game.boxshot,class: 'img-responsive img-rounded'), game %>
  	    </div>
    <% if i%3 == 2%>
  	 </div> 
     <br/>
    <%end%>
    <% i = i+1%>
   <%end%>
 
</div>



 <!-- -->

app/views/site/index.html.erb
<%= render 'catalog' %>